/**
 * Music that fits reels, to find and add yourself: Auto Tournament ships no
 * music and downloads none (bring your own: music.ts). These are tracks we
 * picked by ear on Pixabay; the admin opens a page, downloads the track there
 * under the Pixabay Content License and uploads it to the library.
 * THIRD-PARTY-MEDIA.md says what that license allows.
 *
 * `contentId`: registered with YouTube Content ID by its creator, so a YouTube
 * upload with it can get a claim (ads on the video; no strike).
 */
export interface MusicSuggestion {
  title: string;
  artist: string;
  genre: string;
  /** Its page on Pixabay. */
  page: string;
  contentId: boolean;
}

export const MUSIC_SUGGESTIONS: readonly MusicSuggestion[] = [
  {
    title: 'Dark Ambient',
    artist: 'sharvarion',
    genre: 'ambient',
    page: 'https://pixabay.com/music/ambient-dark-ambient-126122/',
    contentId: true,
  },
  {
    title: 'The Outerworld - Under The Stars',
    artist: 'Daljit_Kundi',
    genre: 'ambient',
    page: 'https://pixabay.com/music/ambient-the-outerworld-under-the-stars-462050/',
    contentId: false,
  },
  {
    title: 'Upbeat - Get It',
    artist: 'Easy_Eva',
    genre: 'beats',
    page: 'https://pixabay.com/music/beats-upbeat-get-it-564064/',
    contentId: false,
  },
  {
    title: 'Chaos',
    artist: 'Grand_Project',
    genre: 'build-up-scenes',
    page: 'https://pixabay.com/music/build-up-scenes-chaos-399944/',
    contentId: true,
  },
  {
    title: 'Documentary Tension',
    artist: 'leberch',
    genre: 'build-up-scenes',
    page: 'https://pixabay.com/music/build-up-scenes-documentary-tension-256156/',
    contentId: true,
  },
  {
    title: 'Uplifting - Friend',
    artist: 'Easy_Eva',
    genre: 'corporate',
    page: 'https://pixabay.com/music/corporate-uplifting-friend-605770/',
    contentId: false,
  },
  {
    title: 'Runaway Lights',
    artist: 'jakob_welik',
    genre: 'dance',
    page: 'https://pixabay.com/music/dance-runaway-lights-463852/',
    contentId: true,
  },
  {
    title: 'Hypnosis (Deep Techno House)',
    artist: 'NverAvetyanMusic',
    genre: 'deep-house',
    page: 'https://pixabay.com/music/deep-house-hypnosis-deep-techno-house-614495/',
    contentId: true,
  },
  {
    title: 'Acid Bonus (Liquid Breakbeat Jungle Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-acid-bonus-liquid-breakbeat-jungle-drum-and-bass-354206/',
    contentId: false,
  },
  {
    title: 'Astral Realms & Ziyal - Binary Galaxies',
    artist: 'Daljit_Kundi',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-astral-realms-amp-ziyal-binary-galaxies-467548/',
    contentId: false,
  },
  {
    title: 'Astral Realms & Ziyal - Voices From Within',
    artist: 'Daljit_Kundi',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-astral-realms-amp-ziyal-voices-from-within-467544/',
    contentId: false,
  },
  {
    title: 'Breakbeat so Breakbeat',
    artist: 'AudioDollar',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-breakbeat-so-breakbeat-614331/',
    contentId: true,
  },
  {
    title: 'Clear Horizons (Liquid Jungle Breakbeat Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-clear-horizons-liquid-jungle-breakbeat-drum-and-bass-356507/',
    contentId: false,
  },
  {
    title: 'Digital Elements (Liquid Jungle Breakbeat Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-digital-elements-liquid-jungle-breakbeat-drum-and-bass-356516/',
    contentId: false,
  },
  {
    title: 'Drum & Bass - DnB Music',
    artist: 'Watermello',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-drum-amp-bass-dnb-music-dampb-drum-and-bass-488391/',
    contentId: true,
  },
  {
    title: 'Harambee - Africa Swahili Drum and Bass',
    artist: 'vjgalaxy',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-harambee-africa-swahili-drum-and-bass-594062/',
    contentId: false,
  },
  {
    title: 'Hopeless Drum and Bass Full',
    artist: 'catch22music',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-hopeless-drum-and-bass-full-369496/',
    contentId: true,
  },
  {
    title: 'Hyper Garden (Jungle Breakbeat Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-hyper-garden-jungle-breakbeat-drum-and-bass-loop-edit-356528/',
    contentId: false,
  },
  {
    title: 'Hyper Garden (Jungle Breakbeat Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-hyper-garden-jungle-breakbeat-drum-and-bass-356529/',
    contentId: false,
  },
  {
    title: 'Information Flow (Liquid Jungle Breakbeat Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-information-flow-liquid-jungle-breakbeat-drum-and-bass-358432/',
    contentId: false,
  },
  {
    title: 'Jungle Waves (Drum&Bass Electronic Inspiring Promo)',
    artist: 'DIMMYSAD',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-jungle-waves-drumampbass-electronic-inspiring-promo-345013/',
    contentId: true,
  },
  {
    title: 'Neon Sky (Liquid Jungle Breakbeat Drum and Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-neon-sky-liquid-jungle-breakbeat-drum-and-bass-356503/',
    contentId: false,
  },
  {
    title: 'Neon Surfer (Liquid Breakbeat Jungle Drum & Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-neon-surfer-liquid-breakbeat-jungle-drum-amp-bass-354198/',
    contentId: false,
  },
  {
    title: 'Proximity (Liquid Drum and Bass)',
    artist: 'penguinmusic',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-proximity-liquid-drum-and-bass-186378/',
    contentId: false,
  },
  {
    title: 'Riding My Bike (Jazzy Liquid Jungle DnB)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-riding-my-bike-jazzy-liquid-jungle-dnb-354215/',
    contentId: false,
  },
  {
    title: 'The Outerworld - Astral Projections',
    artist: 'Daljit_Kundi',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-the-outerworld-astral-projections-480607/',
    contentId: false,
  },
  {
    title: 'The Outerworld - Space & Aviation',
    artist: 'Daljit_Kundi',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-the-outerworld-space-amp-aviation-462059/',
    contentId: false,
  },
  {
    title: 'The Outerworld - Voices From The Past',
    artist: 'Daljit_Kundi',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-the-outerworld-voices-from-the-past-480603/',
    contentId: true,
  },
  {
    title: 'Soulsweeper',
    artist: 'ItsWatR',
    genre: 'dubstep',
    page: 'https://pixabay.com/music/dubstep-soulsweeper-252499/',
    contentId: false,
  },
  {
    title: 'Action Chase Sequence Drive',
    artist: 'alex-morgan',
    genre: 'electronic',
    page: 'https://pixabay.com/music/electro-action-chase-sequence-drive-573649/',
    contentId: true,
  },
  {
    title: 'Electronic - Golden',
    artist: 'Easy_Eva',
    genre: 'electronic',
    page: 'https://pixabay.com/music/electronic-electronic-golden-564082/',
    contentId: false,
  },
  {
    title: 'Shound - Highlights',
    artist: 'WildSpeedRecords',
    genre: 'electronic',
    page: 'https://pixabay.com/music/electronic-shound-highlights-477396/',
    contentId: true,
  },
  {
    title: 'Shound - Jazzed Up',
    artist: 'WildSpeedRecords',
    genre: 'electronic',
    page: 'https://pixabay.com/music/electronic-shound-jazzed-up-477394/',
    contentId: true,
  },
  {
    title: 'Shound - New Paths',
    artist: 'WildSpeedRecords',
    genre: 'electronic',
    page: 'https://pixabay.com/music/electronic-shound-new-paths-477414/',
    contentId: false,
  },
  {
    title: 'Funk Breakbeat',
    artist: 'Kulakovka',
    genre: 'funk',
    page: 'https://pixabay.com/music/funk-funk-breakbeat-266615/',
    contentId: true,
  },
  {
    title: 'Modulator (Funky Music)',
    artist: 'NverAvetyanMusic',
    genre: 'funk',
    page: 'https://pixabay.com/music/funk-modulator-funky-music-613481/',
    contentId: true,
  },
  {
    title: 'Drum And Bass Jungle',
    artist: 'echoes_of_lumen',
    genre: 'future-bass',
    page: 'https://pixabay.com/music/future-bass-drum-and-bass-jungle-583440/',
    contentId: true,
  },
  {
    title: 'Evaporate (Abstract Future Garage)',
    artist: 'NverAvetyanMusic',
    genre: 'future-bass',
    page: 'https://pixabay.com/music/future-bass-evaporate-abstract-future-garage-612778/',
    contentId: true,
  },
  {
    title: 'Beautiful Melody',
    artist: 'alex-morgan',
    genre: 'house',
    page: 'https://pixabay.com/music/house-beautiful-melody-emotional-background-music-587414/',
    contentId: false,
  },
  {
    title: 'Emotional',
    artist: 'Easy_Eva',
    genre: 'house',
    page: 'https://pixabay.com/music/house-emotional-605988/',
    contentId: false,
  },
  {
    title: 'Emotional - Just Friends',
    artist: 'Easy_Eva',
    genre: 'house',
    page: 'https://pixabay.com/music/house-emotional-just-friends-605987/',
    contentId: false,
  },
  {
    title: 'Feel Good - It Feels So Good',
    artist: 'Easy_Eva',
    genre: 'house',
    page: 'https://pixabay.com/music/house-feel-good-it-feels-so-good-605779/',
    contentId: false,
  },
  {
    title: 'July',
    artist: 'Easy_Eva',
    genre: 'house',
    page: 'https://pixabay.com/music/electronic-house-july-605765/',
    contentId: false,
  },
  {
    title: 'Minimal House',
    artist: 'Aurec',
    genre: 'house',
    page: 'https://pixabay.com/music/electronic-minimal-house-612631/',
    contentId: true,
  },
  {
    title: 'Vocal House',
    artist: '9JackJack8',
    genre: 'house',
    page: 'https://pixabay.com/music/house-vocal-house-301199/',
    contentId: true,
  },
  {
    title: 'Bebop Coffee Shop',
    artist: 'alex-morgan',
    genre: 'jazz',
    page: 'https://pixabay.com/music/traditional-jazz-bebop-coffee-shop-517090/',
    contentId: true,
  },
  {
    title: 'Adventure Journey',
    artist: 'The_Mountain',
    genre: 'main-title',
    page: 'https://pixabay.com/music/main-title-adventure-journey-317774/',
    contentId: true,
  },
  {
    title: 'Winning Elevation',
    artist: 'Hot_Dope',
    genre: 'main-title',
    page: 'https://pixabay.com/music/main-title-winning-elevation-111355/',
    contentId: true,
  },
  {
    title: 'Apocalypse (Epic Background Music)',
    artist: 'White_Records',
    genre: 'modern-classical',
    page: 'https://pixabay.com/music/modern-classical-apocalypse-epic-background-music-for-video-stories-full-version-465492/',
    contentId: true,
  },
  {
    title: 'Mysterious Cinematic',
    artist: 'leberch',
    genre: 'mystery',
    page: 'https://pixabay.com/music/mystery-mysterious-cinematic-255712/',
    contentId: true,
  },
  {
    title: 'Happiness',
    artist: 'Easy_Eva',
    genre: 'orchestral',
    page: 'https://pixabay.com/music/orchestral-happiness-606742/',
    contentId: false,
  },
  {
    title: 'Happiness - Let It Go',
    artist: 'Easy_Eva',
    genre: 'orchestral',
    page: 'https://pixabay.com/music/orchestral-happiness-let-it-go-606741/',
    contentId: false,
  },
  {
    title: 'Aggressive Brazilian Phonk 3',
    artist: 'AbsoluteSound',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-aggressive-brazilian-phonk-3-514615/',
    contentId: true,
  },
  {
    title: 'Brazilian Phonk - Phonk',
    artist: 'MondaMusic',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-brazilian-phonk-phonk-542543/',
    contentId: true,
  },
  {
    title: 'Phonk',
    artist: 'The_Mountain',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-567414/',
    contentId: true,
  },
  {
    title: 'Phonk - Phonk Music',
    artist: 'The_Mountain',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-phonk-music-496450/',
    contentId: true,
  },
  {
    title: 'Phonk Aggressive Drift Night',
    artist: 'alex-morgan',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-aggressive-drift-night-573644/',
    contentId: true,
  },
  {
    title: 'Phonk Aura Drift Night Ride',
    artist: 'alex-morgan',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-aura-drift-night-ride-587401/',
    contentId: false,
  },
  {
    title: 'Phonk Instrumental',
    artist: 'Sub_Clair',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-instrumental-588308/',
    contentId: true,
  },
  {
    title: 'Phonk Music',
    artist: 'kiravale',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-music-593661/',
    contentId: true,
  },
  {
    title: 'Phonk Music - Phonk',
    artist: 'XXXDOLM',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-music-phonk-480283/',
    contentId: true,
  },
  {
    title: 'Phonk Songs',
    artist: 'kiravale',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-songs-593656/',
    contentId: true,
  },
  {
    title: 'Sport Phonk',
    artist: 'echoes_of_lumen',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-sport-phonk-584900/',
    contentId: true,
  },
  {
    title: 'Escape Your Love (Upbeat Fashion Pop Dance)',
    artist: 'FASSounds',
    genre: 'pop',
    page: 'https://pixabay.com/music/pop-escape-your-love-upbeat-fashion-pop-dance-412230/',
    contentId: true,
  },
  {
    title: 'Pop - Friends Like Us',
    artist: 'Easy_Eva',
    genre: 'pop',
    page: 'https://pixabay.com/music/pop-pop-friends-like-us-564013/',
    contentId: false,
  },
  {
    title: 'Atmosphere Pulse',
    artist: 'leberch',
    genre: 'pulses',
    page: 'https://pixabay.com/music/pulses-atmosphere-pulse-263075/',
    contentId: true,
  },
  {
    title: 'Emotional - Emotional Music',
    artist: 'Easy_Eva',
    genre: 'small-emotions',
    page: 'https://pixabay.com/music/small-emotions-emotional-emotional-music-605991/',
    contentId: false,
  },
  {
    title: 'Inspiring Emotional',
    artist: 'Easy_Eva',
    genre: 'small-emotions',
    page: 'https://pixabay.com/music/small-emotions-inspiring-emotional-605990/',
    contentId: false,
  },
  {
    title: 'Action Music',
    artist: 'kiravale',
    genre: 'techno-trance',
    page: 'https://pixabay.com/music/techno-trance-action-music-598107/',
    contentId: true,
  },
  {
    title: 'German Techno Cowboy | Uplifting Trance Journey',
    artist: 'NickPanek',
    genre: 'techno-trance',
    page: 'https://pixabay.com/music/techno-trance-german-techno-cowboy-uplifting-trance-journey-300653/',
    contentId: false,
  },
  {
    title: 'Techno No Copyright (Entropy)',
    artist: 'Evgeny_Bardyuzha',
    genre: 'techno-trance',
    page: 'https://pixabay.com/music/techno-trance-techno-no-copyright-entropy-15944/',
    contentId: true,
  },
  {
    title: 'Action Drive Racing Music',
    artist: 'ViacheslavStarostin',
    genre: 'upbeat',
    page: 'https://pixabay.com/music/upbeat-action-drive-racing-music-429957/',
    contentId: true,
  },
  {
    title: 'The Outerworld - Pulsar',
    artist: 'Daljit_Kundi',
    genre: 'upbeat',
    page: 'https://pixabay.com/music/upbeat-the-outerworld-pulsar-480605/',
    contentId: false,
  },
  {
    title: 'Upbeat Music',
    artist: 'The_Mountain',
    genre: 'upbeat',
    page: 'https://pixabay.com/music/old-school-rnb-upbeat-upbeat-music-567448/',
    contentId: true,
  },
  {
    title: 'Thrash Metal for Armageddon or Anything Really',
    artist: 'NickPanek',
    genre: 'metal',
    page: 'https://pixabay.com/music/metal-thrash-metal-for-armageddon-or-anything-really-262859/',
    contentId: false,
  },
  {
    title: 'Eva | Thrash Metal Instrumental',
    artist: 'NickPanek',
    genre: 'metal',
    page: 'https://pixabay.com/music/metal-eva-thrash-metal-instrumental-305034/',
    contentId: false,
  },
  {
    title: '3rd Eye Infected - Intense Speed Metal Instrumental',
    artist: 'NickPanek',
    genre: 'metal',
    page: 'https://pixabay.com/music/metal-3rd-eye-infected-intense-speed-metal-instrumental-231881/',
    contentId: false,
  },
  {
    title: 'ドライブイン (Drive in)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'pop',
    page: 'https://pixabay.com/music/pop-%E3%83%89%E3%83%A9%E3%82%A4%E3%83%96%E3%82%A4%E3%83%B3drive-in-448308/',
    contentId: false,
  },
  {
    title: 'High-Energy Gabber Trance Rave Track',
    artist: 'NickPanek',
    genre: 'techno-trance',
    page: 'https://pixabay.com/music/techno-trance-high-energy-gabber-trance-rave-track-301454/',
    contentId: false,
  },
  {
    title: 'Game Fantasy',
    artist: 'yoshiyuki_tatsuya',
    genre: 'pop',
    page: 'https://pixabay.com/music/pop-game-fantasy-609860/',
    contentId: false,
  },
  {
    title: '測らないで (Don\'t measure)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'pop',
    page: 'https://pixabay.com/music/pop-%E6%B8%AC%E3%82%89%E3%81%AA%E3%81%84%E3%81%A7donx27t-measure-583230/',
    contentId: false,
  },
  {
    title: '蒼穹の向こう側 (Beyond the Azure Sky, Night)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'pop',
    page: 'https://pixabay.com/music/pop-%E8%92%BC%E7%A9%B9%E3%81%AE%E5%90%91%E3%81%93%E3%81%86%E5%81%B4beyond-the-azure-sky-night-575762/',
    contentId: false,
  },
  {
    title: '蒼穹の向こう側 (Beyond the Azure Sky, 6PM)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'pop',
    page: 'https://pixabay.com/music/pop-%E8%92%BC%E7%A9%B9%E3%81%AE%E5%90%91%E3%81%93%E3%81%86%E5%81%B4beyond-the-azure-sky-6pm-575730/',
    contentId: false,
  },
  {
    title: '蒼穹の向こう側 (Beyond the Azure Sky, 12AM)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'pop',
    page: 'https://pixabay.com/music/pop-%E8%92%BC%E7%A9%B9%E3%81%AE%E5%90%91%E3%81%93%E3%81%86%E5%81%B4beyond-the-azure-sky-12am-575729/',
    contentId: false,
  },
  {
    title: 'メカニックセンター (Mechanic center)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-%E3%83%A1%E3%82%AB%E3%83%8B%E3%83%83%E3%82%AF%E3%82%BB%E3%83%B3%E3%82%BF%E3%83%BCmechanic-center-536036/',
    contentId: false,
  },
  {
    title: '地下道場 (Underground dojo)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-%E5%9C%B0%E4%B8%8B%E9%81%93%E5%A0%B4underground-dojo-536034/',
    contentId: false,
  },
  {
    title: 'アレクサ (Alexa theme OST)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'rock',
    page: 'https://pixabay.com/music/rock-%E3%82%A2%E3%83%AC%E3%82%AF%E3%82%B5alexa-theme-ost-501981/',
    contentId: false,
  },
  {
    title: '決戦 (A showdown)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'dubstep',
    page: 'https://pixabay.com/music/dubstep-%E6%B1%BA%E6%88%A6a-showdown-449417/',
    contentId: false,
  },
  {
    title: '殺戮のにおい (The smell of slaughter)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'rock',
    page: 'https://pixabay.com/music/rock-%E6%AE%BA%E6%88%AE%E3%81%AE%E3%81%AB%E3%81%8A%E3%81%84the-smell-of-slaughter-449416/',
    contentId: false,
  },
  {
    title: '最大値 (The maximum value)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'techno-trance',
    page: 'https://pixabay.com/music/techno-trance-%E6%9C%80%E5%A4%A7%E5%80%A4the-maximum-value-448307/',
    contentId: false,
  },
  {
    title: '星の光 (Starlight)',
    artist: 'yoshiyuki_tatsuya',
    genre: 'rock',
    page: 'https://pixabay.com/music/hard-rock-%E6%98%9F%E3%81%AE%E5%85%89-starlight-432882/',
    contentId: false,
  },
];
