/**
 * Import-map shims for runtime-loaded game modules
 * (DESIGN-module-client-api.md §3).
 *
 * A code module is built with React, MUI, the router, i18next and the
 * platform SDK left as bare imports. For each of those specifiers this plugin
 * writes one small ESM file, a *shim*, that re-exports the host's own
 * instance from `globalThis.__AT_SHARED__`, and adds an import map to
 * index.html pointing the specifier at it. The registry the shims read is
 * filled lazily, by `src/module-loader/sharedRegistry.ts`, and only when a
 * code module is loaded, so the main bundle does not grow.
 *
 * Every export name is written out (`export const useState = …`) rather than
 * destructured, so a module importing a name this host does not have fails
 * to link inside `import()`, where the loader catches it and the Modules page
 * says so, instead of getting `undefined` and failing on first render.
 *
 * The names come from the browser build the host actually bundles: Vite's
 * own resolver (browser conditions) finds the file, and `es-module-lexer`
 * reads its exports, following `export *`. A CommonJS package (React 18) has
 * no ESM build to read, and is loaded in Node for its keys instead.
 *
 * The import map is static per host build and never lists modules, so
 * installing a module never touches index.html.
 */

import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { resolve as resolvePath } from 'node:path';
import { init, parse } from 'es-module-lexer';
import type { Plugin, ResolvedConfig } from 'vite';
import {
  SDK_SPECIFIER,
  SHARED_GLOBAL,
  SHARED_SPECIFIERS,
  SHARED_SUBSETS,
  shimStem,
} from '../src/module-loader/sharedSpecifiers';

/** Resolves `specifier` from `importer` to a file path, or null. */
export type Resolver = (specifier: string, importer: string) => Promise<string | null>;

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
// Valid identifiers that cannot be an `export const` binding.
const RESERVED = new Set([
  'await', 'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger', 'default',
  'delete', 'do', 'else', 'enum', 'export', 'extends', 'false', 'finally', 'for', 'function',
  'if', 'implements', 'import', 'in', 'instanceof', 'interface', 'let', 'new', 'null',
  'package', 'private', 'protected', 'public', 'return', 'static', 'super', 'switch', 'this',
  'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with', 'yield',
]);

const stripQuery = (id: string) => id.replace(/[?#].*$/, '');

/**
 * The runtime export names of the module at `file`: its own ESM exports plus
 * everything its `export *` statements pass on (never `default`), or the keys
 * of `module.exports` for a CommonJS file. Type-only exports are skipped.
 */
export async function exportNames(
  file: string,
  resolve: Resolver,
  seen: Set<string> = new Set()
): Promise<Set<string>> {
  const path = stripQuery(file);
  const names = new Set<string>();
  if (seen.has(path)) return names;
  seen.add(path);

  await init;
  const source = await readFile(path, 'utf8');
  const [, exports, , hasModuleSyntax] = parse(source, path);

  if (!hasModuleSyntax) {
    const loaded = createRequire(path)(path) as Record<string, unknown>;
    for (const key of Object.keys(loaded)) names.add(key);
    names.delete('__esModule');
    return names;
  }

  for (const entry of exports) {
    if (entry.typeOnly) continue;
    if (entry.type === 'reexport-all') {
      const target = await resolve(entry.from, path);
      if (!target) throw new Error(`module shims: cannot resolve "${entry.from}" from ${path}`);
      for (const name of await exportNames(target, resolve, seen)) {
        if (name !== 'default') names.add(name);
      }
    } else {
      names.add(entry.name);
    }
  }
  return names;
}

/** The shim for `specifier`, re-exporting every one of `names` from the host's instance. */
export function shimSource(specifier: string, names: Iterable<string>): string {
  const spec = JSON.stringify(specifier);
  const lines = [
    `// Generated by client/vite-plugins/moduleShims.ts: the host's own ${specifier},`,
    `// for game modules loaded at runtime. Filled by src/module-loader/sharedRegistry.ts.`,
    `const m = globalThis[${JSON.stringify(SHARED_GLOBAL)}]?.[${spec}];`,
    `if (!m) throw new Error(${JSON.stringify(`Auto Tournament has not shared ${specifier} with modules`)});`,
    // A CommonJS package can arrive as a namespace whose names live on `default`.
    `const d = m.default;`,
    `const pick = (k) => (k in m ? m[k] : d == null ? undefined : d[k]);`,
    `export default ('default' in m ? m.default : m);`,
  ];
  for (const name of [...names].sort()) {
    if (name === 'default' || !IDENTIFIER.test(name) || RESERVED.has(name)) continue;
    lines.push(`export const ${name} = pick(${JSON.stringify(name)});`);
  }
  return lines.join('\n') + '\n';
}

interface Shim {
  specifier: string;
  /** Path inside the build output, or under the dev prefix. */
  fileName: string;
  source: string;
  names: number;
}

const DEV_PREFIX = '__module-shims/';

async function generateShims(
  root: string,
  resolve: Resolver,
  mode: 'build' | 'serve'
): Promise<Shim[]> {
  const importer = resolvePath(root, 'index.html');
  const shims: Shim[] = [];
  for (const specifier of SHARED_SPECIFIERS) {
    // The SDK's names come from its source; a subset's from the file that
    // re-exports it; everything else from the package the host bundles.
    const subset = SHARED_SUBSETS[specifier];
    const file =
      specifier === SDK_SPECIFIER
        ? resolvePath(root, 'src/module-sdk/index.ts')
        : subset
          ? resolvePath(root, subset)
          : await resolve(specifier, importer);
    if (!file) throw new Error(`module shims: cannot resolve ${specifier}`);
    const names = await exportNames(file, resolve);
    const source = shimSource(specifier, names);
    const stem = shimStem(specifier);
    const hash = createHash('sha256').update(source).digest('hex').slice(0, 8);
    shims.push({
      specifier,
      fileName: mode === 'build' ? `assets/module-shims/${stem}-${hash}.js` : `${DEV_PREFIX}${stem}.js`,
      source,
      names: names.size,
    });
  }
  return shims;
}

/** Node's resolution, for the dev server (where Vite's resolver answers with pre-bundled deps). */
function nodeResolver(): Resolver {
  return async (specifier, importer) => {
    try {
      return createRequire(importer).resolve(specifier);
    } catch {
      return null;
    }
  };
}

export function moduleShims(): Plugin {
  let config: ResolvedConfig;
  let shims: Promise<Shim[]> | null = null;

  const importMap = (list: Shim[]) =>
    JSON.stringify({
      imports: Object.fromEntries(list.map((shim) => [shim.specifier, config.base + shim.fileName])),
    });

  return {
    name: 'at-module-shims',

    configResolved(resolved) {
      config = resolved;
    },

    async buildStart() {
      if (config.command !== 'build') return;
      const resolve: Resolver = async (specifier, importer) =>
        (await this.resolve(specifier, importer, { skipSelf: true }))?.id ?? null;
      shims = generateShims(config.root, resolve, 'build');
      for (const shim of await shims) {
        this.emitFile({ type: 'asset', fileName: shim.fileName, source: shim.source });
      }
      config.logger.info(
        `module shims: ${(await shims).map((s) => `${s.specifier} (${s.names})`).join(', ')}`
      );
    },

    configureServer(server) {
      shims = generateShims(config.root, nodeResolver(), 'serve');
      const prefix = config.base + DEV_PREFIX;
      server.middlewares.use((req, res, next) => {
        if (!req.url?.startsWith(prefix) || !shims) return next();
        const wanted = stripQuery(req.url.slice(config.base.length));
        shims
          .then((list) => {
            const shim = list.find((s) => s.fileName === wanted);
            if (!shim) {
              res.statusCode = 404;
              res.end();
              return;
            }
            res.setHeader('Content-Type', 'text/javascript; charset=utf-8');
            res.setHeader('Cache-Control', 'no-store');
            res.end(shim.source);
          })
          .catch(next);
      });
    },

    transformIndexHtml: {
      order: 'pre',
      async handler() {
        if (!shims) return [];
        return [
          {
            tag: 'script',
            attrs: { type: 'importmap' },
            children: importMap(await shims),
            injectTo: 'head-prepend',
          },
        ];
      },
    },
  };
}
