/**
 * The music reels can play under: instrumental tracks from Pixabay, picked by
 * ear. The Pixabay licence lets a video use them but not a library pass them
 * on, so each install downloads the ones it plays from Pixabay itself
 * (music.ts) instead of shipping them.
 *
 * `contentId`: Pixabay registered the track with YouTube Content ID, so a
 * YouTube upload with it can get a claim (ads on the video; no strike).
 * `gainDb`: what evens its loudness out with the others, measured (EBU R128)
 * against the middle of the set, -9.6 LUFS, the level the reel music was
 * tuned at.
 */
export interface MusicTrack {
  /** Pixabay's id for it. */
  id: string;
  title: string;
  artist: string;
  /** Pixabay's genre for it (MUSIC_GENRES). */
  genre: MusicGenre;
  /** Its page on Pixabay. */
  page: string;
  /** The MP3 on Pixabay's CDN. */
  audio: string;
  seconds: number;
  contentId: boolean;
  /** Added to its level, in dB, so it sounds as loud as the others. */
  gainDb: number;
}

/** Pixabay's genres, in the order the player lists them. */
export const MUSIC_GENRES = [
  'drum-n-bass',
  'phonk',
  'techno-trance',
  'house',
  'deep-house',
  'future-bass',
  'electronic',
  'funk',
  'upbeat',
  'ambient',
  'pop',
  'dance',
  'beats',
  'small-emotions',
  'corporate',
  'orchestral',
  'jazz',
  'build-up-scenes',
  'dubstep',
  'pulses',
  'mystery',
  'modern-classical',
] as const;
export type MusicGenre = (typeof MUSIC_GENRES)[number];

export const MUSIC_TRACKS: readonly MusicTrack[] = [
  {
    id: '496450',
    title: 'Phonk - Phonk Music',
    artist: 'The_Mountain',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-phonk-music-496450/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/03/06/audio_37df81dfff.mp3',
    seconds: 105,
    contentId: true,
    gainDb: -1.0,
  },
  {
    id: '480283',
    title: 'Phonk Music - Phonk',
    artist: 'XXXDOLM',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-music-phonk-480283/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/02/06/audio_762b543928.mp3',
    seconds: 106,
    contentId: true,
    gainDb: -2.1,
  },
  {
    id: '488391',
    title: 'Drum & Bass - DnB Music',
    artist: 'Watermello',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-drum-amp-bass-dnb-music-dampb-drum-and-bass-488391/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/02/20/audio_ca82a26d8e.mp3',
    seconds: 155,
    contentId: true,
    gainDb: -1.6,
  },
  {
    id: '573644',
    title: 'Phonk Aggressive Drift Night',
    artist: 'alex-morgan',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-aggressive-drift-night-573644/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/07/25/audio_dc9b4de07f.mp3',
    seconds: 103,
    contentId: true,
    gainDb: -0.5,
  },
  {
    id: '15944',
    title: 'Techno No Copyright (Entropy)',
    artist: 'Evgeny_Bardyuzha',
    genre: 'techno-trance',
    page: 'https://pixabay.com/music/techno-trance-techno-no-copyright-entropy-15944/',
    audio: 'https://cdn.pixabay.com/download/audio/2022/01/29/audio_0e6dd4497f.mp3',
    seconds: 173,
    contentId: true,
    gainDb: -1.9,
  },
  {
    id: '567414',
    title: 'Phonk',
    artist: 'The_Mountain',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-567414/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/07/14/audio_008b5cec73.mp3',
    seconds: 100,
    contentId: true,
    gainDb: -1.2,
  },
  {
    id: '356528',
    title: 'Hyper Garden (Jungle Breakbeat Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-hyper-garden-jungle-breakbeat-drum-and-bass-loop-edit-356528/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/06/07/audio_dd502a59f8.mp3',
    seconds: 77,
    contentId: false,
    gainDb: 1.1,
  },
  {
    id: '429957',
    title: 'Action Drive Racing Music',
    artist: 'ViacheslavStarostin',
    genre: 'upbeat',
    page: 'https://pixabay.com/music/upbeat-action-drive-racing-music-429957/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/11/02/audio_1e082f5146.mp3',
    seconds: 211,
    contentId: true,
    gainDb: -0.1,
  },
  {
    id: '588308',
    title: 'Phonk Instrumental',
    artist: 'Sub_Clair',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-instrumental-588308/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/08/19/audio_67b5d86908.mp3',
    seconds: 106,
    contentId: true,
    gainDb: 0.6,
  },
  {
    id: '369496',
    title: 'Hopeless Drum and Bass Full',
    artist: 'catch22music',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-hopeless-drum-and-bass-full-369496/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/07/03/audio_808dbd30b1.mp3',
    seconds: 200,
    contentId: true,
    gainDb: 2.8,
  },
  {
    id: '587401',
    title: 'Phonk Aura Drift Night Ride',
    artist: 'alex-morgan',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-aura-drift-night-ride-587401/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/08/17/audio_e8ba1491dc.mp3',
    seconds: 142,
    contentId: false,
    gainDb: -0.3,
  },
  {
    id: '300653',
    title: 'German Techno Cowboy | Uplifting Trance Journey',
    artist: 'NickPanek',
    genre: 'techno-trance',
    page: 'https://pixabay.com/music/techno-trance-german-techno-cowboy-uplifting-trance-journey-300653/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/02/13/audio_ada61ed80e.mp3',
    seconds: 144,
    contentId: false,
    gainDb: 5.0,
  },
  {
    id: '266615',
    title: 'Funk Breakbeat',
    artist: 'Kulakovka',
    genre: 'funk',
    page: 'https://pixabay.com/music/funk-funk-breakbeat-266615/',
    audio: 'https://cdn.pixabay.com/download/audio/2024/11/20/audio_2bb38a87fd.mp3',
    seconds: 147,
    contentId: true,
    gainDb: 2.0,
  },
  {
    id: '593661',
    title: 'Phonk Music',
    artist: 'kiravale',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-music-593661/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/08/28/audio_fc32ac050f.mp3',
    seconds: 92,
    contentId: true,
    gainDb: -0.4,
  },
  {
    id: '584900',
    title: 'Sport Phonk',
    artist: 'echoes_of_lumen',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-sport-phonk-584900/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/08/13/audio_9921621bd7.mp3',
    seconds: 121,
    contentId: true,
    gainDb: -0.7,
  },
  {
    id: '583440',
    title: 'Drum And Bass Jungle',
    artist: 'echoes_of_lumen',
    genre: 'future-bass',
    page: 'https://pixabay.com/music/future-bass-drum-and-bass-jungle-583440/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/08/11/audio_146b1aa60b.mp3',
    seconds: 199,
    contentId: true,
    gainDb: 0.6,
  },
  {
    id: '593656',
    title: 'Phonk Songs',
    artist: 'kiravale',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-phonk-songs-593656/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/08/28/audio_3f46f44ec9.mp3',
    seconds: 77,
    contentId: true,
    gainDb: -0.4,
  },
  {
    id: '598107',
    title: 'Action Music',
    artist: 'kiravale',
    genre: 'techno-trance',
    page: 'https://pixabay.com/music/techno-trance-action-music-598107/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/05/audio_90f7f4c7cb.mp3',
    seconds: 110,
    contentId: true,
    gainDb: 0.1,
  },
  {
    id: '614331',
    title: 'Breakbeat so Breakbeat',
    artist: 'AudioDollar',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-breakbeat-so-breakbeat-614331/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/10/02/audio_8570ab1926.mp3',
    seconds: 166,
    contentId: true,
    gainDb: -0.1,
  },
  {
    id: '345013',
    title: 'Jungle Waves (Drum&Bass Electronic Inspiring Promo)',
    artist: 'DIMMYSAD',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-jungle-waves-drumampbass-electronic-inspiring-promo-345013/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/05/21/audio_fa20813ea6.mp3',
    seconds: 132,
    contentId: true,
    gainDb: -1.1,
  },
  {
    id: '614495',
    title: 'Hypnosis (Deep Techno House)',
    artist: 'NverAvetyanMusic',
    genre: 'deep-house',
    page: 'https://pixabay.com/music/deep-house-hypnosis-deep-techno-house-614495/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/10/03/audio_1e741675d8.mp3',
    seconds: 180,
    contentId: true,
    gainDb: -2.5,
  },
  {
    id: '613481',
    title: 'Modulator (Funky Music)',
    artist: 'NverAvetyanMusic',
    genre: 'funk',
    page: 'https://pixabay.com/music/funk-modulator-funky-music-613481/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/10/01/audio_11b188ab08.mp3',
    seconds: 153,
    contentId: true,
    gainDb: -1.5,
  },
  {
    id: '612778',
    title: 'Evaporate (Abstract Future Garage)',
    artist: 'NverAvetyanMusic',
    genre: 'future-bass',
    page: 'https://pixabay.com/music/future-bass-evaporate-abstract-future-garage-612778/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/30/audio_4bc1dc26b2.mp3',
    seconds: 180,
    contentId: true,
    gainDb: -1.3,
  },
  {
    id: '462050',
    title: 'The Outerworld - Under The Stars',
    artist: 'Daljit_Kundi',
    genre: 'ambient',
    page: 'https://pixabay.com/music/ambient-the-outerworld-under-the-stars-462050/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/01/06/audio_8537391c2d.mp3',
    seconds: 491,
    contentId: false,
    gainDb: -0.8,
  },
  {
    id: '480603',
    title: 'The Outerworld - Voices From The Past',
    artist: 'Daljit_Kundi',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-the-outerworld-voices-from-the-past-480603/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/02/06/audio_cbd60ec338.mp3',
    seconds: 408,
    contentId: true,
    gainDb: -2.4,
  },
  {
    id: '467548',
    title: 'Astral Realms & Ziyal - Binary Galaxies',
    artist: 'Daljit_Kundi',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-astral-realms-amp-ziyal-binary-galaxies-467548/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/01/16/audio_875e1cf72d.mp3',
    seconds: 467,
    contentId: false,
    gainDb: 1.5,
  },
  {
    id: '480607',
    title: 'The Outerworld - Astral Projections',
    artist: 'Daljit_Kundi',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-the-outerworld-astral-projections-480607/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/02/06/audio_2329792ddb.mp3',
    seconds: 457,
    contentId: false,
    gainDb: -3.1,
  },
  {
    id: '186378',
    title: 'Proximity (Liquid Drum and Bass)',
    artist: 'penguinmusic',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-proximity-liquid-drum-and-bass-186378/',
    audio: 'https://cdn.pixabay.com/download/audio/2024/01/16/audio_f36bbe061a.mp3',
    seconds: 76,
    contentId: false,
    gainDb: 0.4,
  },
  {
    id: '462059',
    title: 'The Outerworld - Space & Aviation',
    artist: 'Daljit_Kundi',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-the-outerworld-space-amp-aviation-462059/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/01/06/audio_f34bd0c4e3.mp3',
    seconds: 495,
    contentId: false,
    gainDb: 0.1,
  },
  {
    id: '480605',
    title: 'The Outerworld - Pulsar',
    artist: 'Daljit_Kundi',
    genre: 'upbeat',
    page: 'https://pixabay.com/music/upbeat-the-outerworld-pulsar-480605/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/02/06/audio_2b0739329a.mp3',
    seconds: 433,
    contentId: false,
    gainDb: -2.4,
  },
  {
    id: '467544',
    title: 'Astral Realms & Ziyal - Voices From Within',
    artist: 'Daljit_Kundi',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-astral-realms-amp-ziyal-voices-from-within-467544/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/01/16/audio_27082b92d4.mp3',
    seconds: 461,
    contentId: false,
    gainDb: 1.3,
  },
  {
    id: '354215',
    title: 'Riding My Bike (Jazzy Liquid Jungle DnB)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-riding-my-bike-jazzy-liquid-jungle-dnb-354215/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/06/04/audio_c6af580f01.mp3',
    seconds: 113,
    contentId: false,
    gainDb: 5.4,
  },
  {
    id: '356529',
    title: 'Hyper Garden (Jungle Breakbeat Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-hyper-garden-jungle-breakbeat-drum-and-bass-356529/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/06/07/audio_a67e673ed7.mp3',
    seconds: 112,
    contentId: false,
    gainDb: 2.1,
  },
  {
    id: '358432',
    title: 'Information Flow (Liquid Jungle Breakbeat Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-information-flow-liquid-jungle-breakbeat-drum-and-bass-358432/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/06/11/audio_fc21a1ef0c.mp3',
    seconds: 180,
    contentId: false,
    gainDb: 2.9,
  },
  {
    id: '354206',
    title: 'Acid Bonus (Liquid Breakbeat Jungle Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-acid-bonus-liquid-breakbeat-jungle-drum-and-bass-354206/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/06/04/audio_2a59b8e916.mp3',
    seconds: 130,
    contentId: false,
    gainDb: 2.9,
  },
  {
    id: '356516',
    title: 'Digital Elements (Liquid Jungle Breakbeat Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-digital-elements-liquid-jungle-breakbeat-drum-and-bass-356516/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/06/07/audio_9297cc17b5.mp3',
    seconds: 119,
    contentId: false,
    gainDb: 2.9,
  },
  {
    id: '356507',
    title: 'Clear Horizons (Liquid Jungle Breakbeat Drum And Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-clear-horizons-liquid-jungle-breakbeat-drum-and-bass-356507/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/06/07/audio_ad6f9fa48a.mp3',
    seconds: 89,
    contentId: false,
    gainDb: 3.8,
  },
  {
    id: '354198',
    title: 'Neon Surfer (Liquid Breakbeat Jungle Drum & Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-neon-surfer-liquid-breakbeat-jungle-drum-amp-bass-354198/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/06/04/audio_d4d41d5020.mp3',
    seconds: 158,
    contentId: false,
    gainDb: 1.1,
  },
  {
    id: '477394',
    title: 'Shound - Jazzed Up',
    artist: 'WildSpeedRecords',
    genre: 'electronic',
    page: 'https://pixabay.com/music/electronic-shound-jazzed-up-477394/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/01/31/audio_407e54beb8.mp3',
    seconds: 200,
    contentId: true,
    gainDb: 0.6,
  },
  {
    id: '356503',
    title: 'Neon Sky (Liquid Jungle Breakbeat Drum and Bass)',
    artist: 'Musinova',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-neon-sky-liquid-jungle-breakbeat-drum-and-bass-356503/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/06/07/audio_83797539a6.mp3',
    seconds: 100,
    contentId: false,
    gainDb: 1.5,
  },
  {
    id: '477396',
    title: 'Shound - Highlights',
    artist: 'WildSpeedRecords',
    genre: 'electronic',
    page: 'https://pixabay.com/music/electronic-shound-highlights-477396/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/01/31/audio_2a3d518b3e.mp3',
    seconds: 289,
    contentId: true,
    gainDb: -0.1,
  },
  {
    id: '477414',
    title: 'Shound - New Paths',
    artist: 'WildSpeedRecords',
    genre: 'electronic',
    page: 'https://pixabay.com/music/electronic-shound-new-paths-477414/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/01/31/audio_94083f2508.mp3',
    seconds: 295,
    contentId: false,
    gainDb: 0.6,
  },
  {
    id: '412230',
    title: 'Escape Your Love (Upbeat Fashion Pop Dance)',
    artist: 'FASSounds',
    genre: 'pop',
    page: 'https://pixabay.com/music/pop-escape-your-love-upbeat-fashion-pop-dance-412230/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/09/29/audio_77a36612dd.mp3',
    seconds: 138,
    contentId: true,
    gainDb: -1.5,
  },
  {
    id: '301199',
    title: 'Vocal House',
    artist: '9JackJack8',
    genre: 'house',
    page: 'https://pixabay.com/music/house-vocal-house-301199/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/02/14/audio_1a18f59a09.mp3',
    seconds: 170,
    contentId: true,
    gainDb: -0.2,
  },
  {
    id: '605765',
    title: 'July',
    artist: 'Easy_Eva',
    genre: 'house',
    page: 'https://pixabay.com/music/electronic-house-july-605765/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/18/audio_02e0cf6130.mp3',
    seconds: 155,
    contentId: false,
    gainDb: 3.9,
  },
  {
    id: '605987',
    title: 'Emotional - Just Friends',
    artist: 'Easy_Eva',
    genre: 'house',
    page: 'https://pixabay.com/music/house-emotional-just-friends-605987/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/24/audio_83a7ea1d9d.mp3',
    seconds: 230,
    contentId: false,
    gainDb: 1.8,
  },
  {
    id: '606741',
    title: 'Happiness - Let It Go',
    artist: 'Easy_Eva',
    genre: 'orchestral',
    page: 'https://pixabay.com/music/orchestral-happiness-let-it-go-606741/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/19/audio_9445d1ef78.mp3',
    seconds: 192,
    contentId: false,
    gainDb: 0.4,
  },
  {
    id: '605988',
    title: 'Emotional',
    artist: 'Easy_Eva',
    genre: 'house',
    page: 'https://pixabay.com/music/house-emotional-605988/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/24/audio_abc19209f1.mp3',
    seconds: 94,
    contentId: false,
    gainDb: 2.6,
  },
  {
    id: '606742',
    title: 'Happiness',
    artist: 'Easy_Eva',
    genre: 'orchestral',
    page: 'https://pixabay.com/music/orchestral-happiness-606742/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/19/audio_82aa896572.mp3',
    seconds: 72,
    contentId: false,
    gainDb: 0.8,
  },
  {
    id: '605770',
    title: 'Uplifting - Friend',
    artist: 'Easy_Eva',
    genre: 'corporate',
    page: 'https://pixabay.com/music/corporate-uplifting-friend-605770/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/18/audio_6f6775300d.mp3',
    seconds: 203,
    contentId: false,
    gainDb: 0.9,
  },
  {
    id: '605991',
    title: 'Emotional - Emotional Music',
    artist: 'Easy_Eva',
    genre: 'small-emotions',
    page: 'https://pixabay.com/music/small-emotions-emotional-emotional-music-605991/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/18/audio_6cdb88546d.mp3',
    seconds: 55,
    contentId: false,
    gainDb: 3.1,
  },
  {
    id: '605990',
    title: 'Inspiring Emotional',
    artist: 'Easy_Eva',
    genre: 'small-emotions',
    page: 'https://pixabay.com/music/small-emotions-inspiring-emotional-605990/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/18/audio_4d2efbafba.mp3',
    seconds: 66,
    contentId: false,
    gainDb: 2.8,
  },
  {
    id: '564064',
    title: 'Upbeat - Get It',
    artist: 'Easy_Eva',
    genre: 'beats',
    page: 'https://pixabay.com/music/beats-upbeat-get-it-564064/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/07/14/audio_30b613eea5.mp3',
    seconds: 153,
    contentId: false,
    gainDb: 0.5,
  },
  {
    id: '564013',
    title: 'Pop - Friends Like Us',
    artist: 'Easy_Eva',
    genre: 'pop',
    page: 'https://pixabay.com/music/pop-pop-friends-like-us-564013/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/07/14/audio_47e9196877.mp3',
    seconds: 236,
    contentId: false,
    gainDb: 0.4,
  },
  {
    id: '605779',
    title: 'Feel Good - It Feels So Good',
    artist: 'Easy_Eva',
    genre: 'house',
    page: 'https://pixabay.com/music/house-feel-good-it-feels-so-good-605779/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/24/audio_b84b3e7391.mp3',
    seconds: 152,
    contentId: false,
    gainDb: 0.4,
  },
  {
    id: '564082',
    title: 'Electronic - Golden',
    artist: 'Easy_Eva',
    genre: 'electronic',
    page: 'https://pixabay.com/music/electronic-electronic-golden-564082/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/07/14/audio_2fe5a96fb6.mp3',
    seconds: 264,
    contentId: false,
    gainDb: 0.4,
  },
  {
    id: '612631',
    title: 'Minimal House',
    artist: 'Aurec',
    genre: 'house',
    page: 'https://pixabay.com/music/electronic-minimal-house-612631/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/09/29/audio_fb02fe6b1e.mp3',
    seconds: 224,
    contentId: true,
    gainDb: 4.2,
  },
  {
    id: '587414',
    title: 'Beautiful Melody',
    artist: 'alex-morgan',
    genre: 'house',
    page: 'https://pixabay.com/music/house-beautiful-melody-emotional-background-music-587414/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/08/17/audio_c7aa356da4.mp3',
    seconds: 167,
    contentId: false,
    gainDb: -0.2,
  },
  {
    id: '567448',
    title: 'Upbeat Music',
    artist: 'The_Mountain',
    genre: 'upbeat',
    page: 'https://pixabay.com/music/old-school-rnb-upbeat-upbeat-music-567448/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/07/14/audio_dbc82636cd.mp3',
    seconds: 196,
    contentId: true,
    gainDb: -0.1,
  },
  {
    id: '463852',
    title: 'Runaway Lights',
    artist: 'jakob_welik',
    genre: 'dance',
    page: 'https://pixabay.com/music/dance-runaway-lights-463852/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/01/10/audio_860fa8d78c.mp3',
    seconds: 189,
    contentId: true,
    gainDb: 3.5,
  },
  {
    id: '573649',
    title: 'Action Chase Sequence Drive',
    artist: 'alex-morgan',
    genre: 'electronic',
    page: 'https://pixabay.com/music/electro-action-chase-sequence-drive-573649/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/07/25/audio_042a283ee5.mp3',
    seconds: 149,
    contentId: true,
    gainDb: -0.6,
  },
  {
    id: '517090',
    title: 'Bebop Coffee Shop',
    artist: 'alex-morgan',
    genre: 'jazz',
    page: 'https://pixabay.com/music/traditional-jazz-bebop-coffee-shop-517090/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/04/18/audio_fa1ced1b14.mp3',
    seconds: 157,
    contentId: true,
    gainDb: 0.3,
  },
  {
    id: '594062',
    title: 'Harambee - Africa Swahili Drum and Bass',
    artist: 'vjgalaxy',
    genre: 'drum-n-bass',
    page: 'https://pixabay.com/music/drum-n-bass-harambee-africa-swahili-drum-and-bass-594062/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/08/29/audio_c2acf63066.mp3',
    seconds: 184,
    contentId: false,
    gainDb: 4.5,
  },
  {
    id: '514615',
    title: 'Aggressive Brazilian Phonk 3',
    artist: 'AbsoluteSound',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-aggressive-brazilian-phonk-3-514615/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/04/11/audio_3059ca30d8.mp3',
    seconds: 96,
    contentId: true,
    gainDb: -6.5,
  },
  {
    id: '256156',
    title: 'Documentary Tension',
    artist: 'leberch',
    genre: 'build-up-scenes',
    page: 'https://pixabay.com/music/build-up-scenes-documentary-tension-256156/',
    audio: 'https://cdn.pixabay.com/download/audio/2024/10/28/audio_d2836992ac.mp3',
    seconds: 106,
    contentId: true,
    gainDb: 1.8,
  },
  {
    id: '542543',
    title: 'Brazilian Phonk - Phonk',
    artist: 'MondaMusic',
    genre: 'phonk',
    page: 'https://pixabay.com/music/phonk-brazilian-phonk-phonk-542543/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/06/09/audio_a8edb35d86.mp3',
    seconds: 44,
    contentId: true,
    gainDb: -4.4,
  },
  {
    id: '263075',
    title: 'Atmosphere Pulse',
    artist: 'leberch',
    genre: 'pulses',
    page: 'https://pixabay.com/music/pulses-atmosphere-pulse-263075/',
    audio: 'https://cdn.pixabay.com/download/audio/2024/11/11/audio_66d34aa310.mp3',
    seconds: 126,
    contentId: true,
    gainDb: 4.6,
  },
  {
    id: '255712',
    title: 'Mysterious Cinematic',
    artist: 'leberch',
    genre: 'mystery',
    page: 'https://pixabay.com/music/mystery-mysterious-cinematic-255712/',
    audio: 'https://cdn.pixabay.com/download/audio/2024/10/27/audio_24ed338cef.mp3',
    seconds: 114,
    contentId: true,
    gainDb: 6.9,
  },
  {
    id: '252499',
    title: 'Soulsweeper',
    artist: 'ItsWatR',
    genre: 'dubstep',
    page: 'https://pixabay.com/music/dubstep-soulsweeper-252499/',
    audio: 'https://cdn.pixabay.com/download/audio/2024/10/18/audio_883a8b2ed8.mp3',
    seconds: 212,
    contentId: false,
    gainDb: -2.0,
  },
  {
    id: '399944',
    title: 'Chaos',
    artist: 'Grand_Project',
    genre: 'build-up-scenes',
    page: 'https://pixabay.com/music/build-up-scenes-chaos-399944/',
    audio: 'https://cdn.pixabay.com/download/audio/2025/09/05/audio_d54f7dce0f.mp3',
    seconds: 182,
    contentId: true,
    gainDb: -0.9,
  },
  {
    id: '465492',
    title: 'Apocalypse (Epic Background Music)',
    artist: 'White_Records',
    genre: 'modern-classical',
    page: 'https://pixabay.com/music/modern-classical-apocalypse-epic-background-music-for-video-stories-full-version-465492/',
    audio: 'https://cdn.pixabay.com/download/audio/2026/01/14/audio_4331d0ec39.mp3',
    seconds: 213,
    contentId: true,
    gainDb: 0.3,
  },
];
